# Generated by Django 6.0.3 on 2026-03-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default='https://via.placeholder.com/150'),
        ),
    ]
